---

- name: Download Inspector agent
  get_url:
    url: http://inspector-agent.amazonaws.com/linux/latest/install
    dest: /usr/local/src/amazon-inspector-install
    mode: 0755

- name: Install Inspector agent
  command: /usr/bin/env bash /usr/local/src/amazon-inspector-install
  args:
    creates: "/etc/init.d/awsagent"

- name: Ensure inspector agent service is running.
  service:
    name: awsagent
    state: "started"
    enabled: yes
